name: 'Sort Markdown links'
description: 'sort links'
branding:
  icon: 'code'
  color: 'orange'
inputs:
  md-file-path:
    description: 'markdown file to load'
    required: true
    default: 'README.md'
  github-token:
    description: 'github token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'